### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by SuperAdam47** [Xenophilicy/Decorations#7]
[Server thread/CRITICAL]: ErrorException: "Undefined index: mug" (EXCEPTION) in "plugins/Decorations-master/src/Xenophilicy/Decorations/archive/PlayerArchive" at line 58

other player pickup my placed mug

**Comment by SuperAdam47** [comment]
and 1 suggestion:
spawnLimit change to buyLimit
maybe better this

**Comment by Xenophilicy** [comment]
> and 1 suggestion:
> spawnLimit change to buyLimit
> maybe better this

Would both be acceptable? Take this example into consideration for me:

A player buys a mug and puts the item in their inventory. He then places the item in a chest for later use. This chest is blown up by an explosion and the item is destroyed. That player has permanantly lost a decoration slot to purchase new models. 

This is why I made the limit on placing, because it doesn't matter how many you buy in this case. As long as it counts the number of *placed* decorations, they will have no issues like this one.

**Comment by Xenophilicy** [comment]
> [Server thread/CRITICAL]: ErrorException: "Undefined index: mug" (EXCEPTION) in "plugins/Decorations-master/src/Xenophilicy/Decorations/archive/PlayerArchive" at line 58
> 
> other player pickup my placed mug

I'll look into this in just one second, it's an entity owner tag issue. I'll let you know when I've committed the changes.
